import { createSlice } from "@reduxjs/toolkit";

// Create a Redux slice for managing the theme state
const themeSlice = createSlice({
	// The `name` field represents the name of the slice in the Redux state
	name: "theme",
	initialState: {
		// The `darkMode` field is set based on the value stored in localStorage or defaults to `false`
		darkMode: localStorage.getItem("darkMode") === "true" || false,
	},
	reducers: {
		// The `toggleDarkMode` reducer toggles the `darkMode` field and updates localStorage
		toggleDarkMode: (state) => {
			state.darkMode = !state.darkMode;
			localStorage.setItem("darkMode", state.darkMode);
		},
	},
});

// Export the action creator for the `toggleDarkMode` reducer
export const { toggleDarkMode } = themeSlice.actions;
// Export a selector function to access the `darkMode` field from the Redux state
export const selectDarkMode = (state) => state.theme.darkMode;
// Export the reducer function generated by `createSlice`
export default themeSlice.reducer;
